### ISSUE TITLE
Multi region / zone support - Topology

### ISSUE THREAD

**Issue by benosman** [spegel-org/spegel#461]
### Describe the problem to be solved

I have some multi region clusters and while I'd like to use Spegel, I'm concerned it will lose some effectiveness due to some of my nodes being in different regions.

The latency between the nodes is enough that I would prefer they fetch images from the internet rather than across region. However, I'd still like for nodes in the same region/zone to be able to share images between themselves.

When searching for this, I noticed this reddit thread
https://www.reddit.com/r/kubernetes/comments/11jc0ck/comment/jb465v0/

I wondered if you'd thought any more about implementing support for this kind of thing.

In the meantime, if I use node selectors to limit the spegel daemonsets to just one of my zones, would that mean the others simply do not participate in the sharing?

**Comment by bittrance** [comment]
Alas, there is still no explicit topological support yet, but it should be possible to create disjunct clusters by installing the spegel Helm chart twice with different release names and different node selectors, e.g.:
```
$ helm upgrade --wait --install --namespace=spegel spegel-1 ./charts/spegel \
              --set "image.repository=ghcr.io/spegel-org/spegel" \
              --set "image.tag=$TAG" \
              --set "nodeSelector.group=one"
$ helm upgrade --wait --install --namespace=spegel spegel-2 ./charts/spegel \
              --set "image.repository=ghcr.io/spegel-org/spegel" \
              --set "image.tag=$TAG" \
              --set "nodeSelector.group=two        
```

**Comment by benosman** [comment]
Thank you for the helpful reply, that would work for me - I will try it out! :)

**Comment by phillebaba** [comment]
This is a question that has been raised a couple of time before, but I have not put too much thought into this. Mostly because the problem is right now theoretical. Either way it is worth discussing, at minimum we should add documentation about this for future users.

What @bittrance mentioned should work even if I have never tested this myself. What you would end up with are separate Spegel clusters which would not share images between each other. I think this is the simplest solution right now to get something working. It does not really add any overhead as each node would run a single pod anyways.

 There are two aspects of this issue, cost and performance. Cross zone/region transfer costs is something that users would want to reduce by giving priority to same region/zone nodes first. The other aspect is as you state performance. In some cases serving images  across regions/zones could be faster than pulling from the internet, but that really depends on your infrastructure.

I see this as two separate features, one is isolated clustering where groups of nodes only pull images from each other. The other is a prioritization where same region/zone is preferred first.

**Comment by phillebaba** [comment]
@benosman did you have a chance to validate the suggestion from @bittrance. I am considering adding this to the FAQ if it was useful.
