### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by bc185174** [spegel-org/spegel#484]
### Describe the problem to be solved

When spegel first pulls an image, the responses from spegel seem to always be 500s which is not very helpful.

- 401/403s on the image pull secrets produce a 500 status code.
- Image not found also produces a 500 error and not a 404 status code.

### Proposed solution to the problem

Improve handling of responses and respond with correct status codes instead of generic 500.

**Comment by bittrance** [comment]
Just so I understand correctly, is this on v0.0.22?

**Comment by bittrance** [comment]
Can you elaborate on the 401/403 errors? spegel does not talk to registries, but simply allows distributed access to what containerd already has in its local store, so I don't think it would normally encounter permission errors; spegel is not a pull-through registry. Are you able to produce a log extract? Remember to include both logs from the forwarding and the receiving spegel pods.

It is true that there are some errors that are turned to 500, but this should not normally happen. spegel replies 404 if no pod is advertising the layer requested. Most 500 cases seems to result from some spegel pod advertising the layer, but cannot then find it in its local containerd store. For this case, 500 can be seen as a reasonable response, since it results from an internal inconsistency in spegel - rerequesting the layer may well produce a different result. We suspect this inconsistency may be a bug in spegel, or possibly some quirk in containerd.

**Comment by phillebaba** [comment]
The status codes wont change because I want Spegel to pass any OCI distribution spec conformance tests. The returned code will for the most part be 200 or 404, unless its an actual internal error where 500 will be returned. As @bittrance stated this was not fixed until v0.0.22.

I do however think that we can be a bit more descriptive in the errors that are returned in the registry, which would show up in the request logs. This way it will be a bit easier to understand why a request did not succeed. Is that something that you are looking for @bc185174?

**Comment by bc185174** [comment]
Yeah so we got this response and it was only resolved after we fixed an issue with a pull secret. In the image pull error event, we see a 500 status code reported.

But here is the log from spegel.

```
{
  "level": "error",
  "ts": 1715765628.8617482,
  "caller": "gin@v0.0.9/logger.go:62",
  "msg": "",
  "path": "<redacted>",
  "status": 500,
  "method": "HEAD",
  "latency": 0.000743547,
  "ip": "100.127.108.64",
  "handler": "mirror",
  "error": "mirror resolve retries exhausted for key: <redacted>",
  "stacktrace": "github.com/xenitab/pkg/gin.NewEngine.Logger.func1\n\t/go/pkg/mod/github.com/xenitab/pkg/gin@v0.0.9/logger.go:62\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009"
}
```

> The status codes wont change because I want Spegel to pass any OCI distribution spec conformance tests. 

Yeah I 100% agree and will update to v0.0.22, thanks @bittrance and @phillebaba!

> I do however think that we can be a bit more descriptive in the errors that are returned in the registry, which would show up in the request logs. This way it will be a bit easier to understand why a request did not succeed. Is that something that you are looking for @bc185174?

Yeah I think this makes sense and would be more what I'd look for. From the logs its quite difficult to analyse and understand _why_ something has happened.

**Comment by bittrance** [comment]
That log entry was fixed recently and should now be 404.

The story in your case goes something like this:

1. containerd asks its mirror for the image
2. spegel can't find it, replying 500 (now fixed to 404)
3. containerd uses its default strategy of pullig from the registry
4. registry replies 401/403

Once the pull secret is fixed:

1. containerd asks its mirror for the image
2. spegel can't find it, replying 500 (now fixed to 404)
3. containerd uses its default strategy of pullig from the registry
4. registry replies with image manifest and layers
5. spegel detects manifest and layers in contatinerd store and advertises them to its peers

After that, spegel pods should be able to handle all subsequent requests for that image by any containerd.
